### ISSUE TITLE
IMX8M UART recieve not working

### ISSUE THREAD

**Issue by Siva-Detect123** [TechNexion/freertos-tn#5]
Hi @richard-hu @ray-chang ,

While testing the M4 example code we noticed that the UART receive wouldn't work no matter what port we used. But using the same UART in Linux the UART receive works. Can you help us in solving this issue

Thanks and regards,
Siva

**Comment by richard-hu** [comment]
Hello, @Siva-Detect123 :

Thanks for your feedback.

We already confirm this issue.
The issue is raised to the highest priority.
We will fix this issue as soon as possible.

We also consider FreeRTOS SDK 2.3 is slight outdating for i.mx8m.
We would like to upgrade to latest SDK 2.5.1 as well.

Thank you~!!!

BR,

Richard

**Comment by Siva-Detect123** [comment]
@richard-hu 

Thanks for the prompt reply.. 

I will do try to solve the issue on my own.. Will post if there is any updates!!

**Comment by richard-hu** [comment]
@Siva-Detect123 

Good news~!!!
We figure out the problem and fix this bug.
 
We find the PIINMUX settings for _UART3_TXD is wrong.
After i correct it, then 'receive' of UART3 works well.

boards/pico-8m-m4/demo_apps/hello_world/fsl_iomuxc.h
`
-#define IOMUXC_UART3_TXD_UART3_TX           0x30330248, 0x0, 0x30330504, 0x3, 0x303304b0
`
`
+#define IOMUXC_UART3_TXD_UART3_TX          0x30330248, 0x0, 0x00000000, 0x0, 0x303304b0
`

We already push the patch to freertos-tn github.
[fix UART3 can't receive](https://github.com/TechNexion/freertos-tn/commit/c29a9bde5db87f9589a6bf6e8de8701d1cae4f2d)

Would you please help me validate if the issue is fixed on your side? 

Thanks for your feedback again~!!!

BR,

Richard

**Comment by Siva-Detect123** [comment]
Thanks :)

**Comment by richard-hu** [comment]
@Siva-Detect123 

We just upgrade McuXpresso SDK to 2.5.1 version.
[mcuxpresso_sdk_2.5.x_imx8](https://github.com/TechNexion/freertos-tn/tree/mcuxpresso_sdk_2.5.x_imx8)
It might be an another option for u.

BR,

Richard
