### ISSUE TITLE
FreeRTOS 2.5 for IMX7D, IMX6?

### ISSUE THREAD

**Issue by Livius90** [TechNexion/freertos-tn#6]
Is IMX7D and IMX6 are supported in FreeRTOS 2.5 (freertos_2.5.x_imx8)? If it is still not, can you say an estimated time-plan for it?

**Comment by richard-hu** [comment]
Hello, @Livius90 :

Thanks for your feedback~!
i.mx6 doesn't contain MCU core so it would not support FreeRTOS. 
(FreeRTOS runs in MCU core(cortex-m4) inside i.mx SOC)
i.mx7D will stay on FreeRTOS 1.0.1, because NXP FreeRTOS BSP keeps on FreeRTOS 1.0.1, and doesn't plan to update it to FreeRTOS 2.X.


i.mx7D isn't in the supported list of FreeRTOS(FreeRTOS is included in MCUXpresso SDK): 
https://mcuxpresso.nxp.com/en/select

It might an effort for us to port i.mx7D to FreeRTOS 2.X from scratch, so currently we don't have clear plan to update it yet.

I'm sorry about it.

BR,

Richard
